# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-17 09:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='host_name',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='\u5305\u7248\u672c')),
                ('test', models.CharField(blank=True, max_length=100, null=True, verbose_name='tet')),
            ],
        ),
        migrations.CreateModel(
            name='OutterIpSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ipAddress', models.GenericIPAddressField(verbose_name='IP\u5730\u5740')),
                ('subnet', models.CharField(blank=True, max_length=100, null=True, verbose_name='\u5b50\u7f51\u63a9\u7801')),
                ('gateway', models.CharField(blank=True, max_length=100, null=True, verbose_name='\u7f51\u5173')),
                ('belong', models.CharField(blank=True, max_length=100, null=True, verbose_name='\u5b50\u7f51\u63a9\u7801')),
                ('fuction', models.CharField(blank=True, max_length=100, null=True, verbose_name='\u7528\u9014')),
                ('isp', models.CharField(blank=True, max_length=100, null=True, verbose_name='ISP')),
                ('status', models.CharField(blank=True, choices=[('0', '\u672a\u4f7f\u7528'), ('1', '\u5df2\u4f7f\u7528')], max_length=30, null=True, verbose_name='\u5305\u72b6\u6001')),
            ],
        ),
        migrations.CreateModel(
            name='package',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='\u5305\u540d')),
                ('lastTime', models.DateTimeField(blank=True, null=True)),
                ('createTime', models.DateTimeField(blank=True, null=True)),
                ('countPackage', models.CharField(blank=True, max_length=100, null=True, verbose_name='\u5305\u6570\u91cf')),
                ('status', models.CharField(blank=True, choices=[('0', '\u5931\u6548'), ('1', '\u542f\u7528')], max_length=30, null=True, verbose_name='\u5305\u72b6\u6001')),
                ('env', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='\u540d\u79f0')),
                ('show', models.BooleanField(default=True, help_text='\u83dc\u5355\u662f\u5426\u663e\u793a\uff0c\u9ed8\u8ba4\u6dfb\u52a0\u4e0d\u663e\u793a', verbose_name='\u662f\u5426\u663e\u793a')),
                ('url', models.CharField(blank=True, default='javascript:void(0)', help_text='\u662f\u5426\u7ed9\u83dc\u5355\u8bbe\u7f6e\u4e00\u4e2aurl\u5730\u5740', max_length=300, null=True, verbose_name='\u83dc\u5355url\u5730\u5740')),
                ('priority', models.IntegerField(blank=True, default=-1, help_text='\u83dc\u5355\u7684\u663e\u793a\u987a\u5e8f\uff0c\u4f18\u5148\u7ea7\u8d8a\u5927\u663e\u793a\u8d8a\u9760\u524d', null=True, verbose_name='\u663e\u793a\u4f18\u5148\u7ea7')),
                ('permission_id', models.IntegerField(error_messages={'field-permission_id': '\u53ea\u80fd\u8f93\u5165\u6570\u5b57'}, help_text='\u7ed9\u83dc\u5355\u8bbe\u7f6e\u4e00\u4e2a\u7f16\u53f7\uff0c\u7528\u4e8e\u6743\u9650\u63a7\u5236', verbose_name='\u6743\u9650\u7f16\u53f7')),
                ('service', models.CharField(blank=True, max_length=100, null=True, verbose_name='\u670d\u52a1')),
                ('describe', models.CharField(blank=True, max_length=100, null=True, verbose_name='\u63cf\u8ff0')),
                ('env', models.IntegerField(blank=True, null=True, verbose_name='\u670d\u52a1\u73af\u5883')),
                ('rchost', models.CharField(blank=True, max_length=100, null=True, verbose_name='RC\u4e3b\u673a')),
                ('status', models.CharField(blank=True, choices=[('0', '\u672a\u521d\u59cb\u5316'), ('1', '\u5df2\u6539\u4e3b\u673a\u540d'), ('2', '\u5df2\u91cd\u65b0\u63a5\u6536key'), ('3', '\u521d\u59cb\u5316\u6210\u529f')], max_length=30, null=True, verbose_name='\u9879\u76ee\u72b6\u6001')),
                ('createTime', models.DateTimeField(blank=True, null=True)),
                ('name_en', models.CharField(max_length=30, unique=True, verbose_name='\u82f1\u6587\u540d')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='\u8d1f\u8d23\u4eba')),
                ('parent', models.ForeignKey(blank=True, help_text='\u5982\u679c\u6dfb\u52a0\u7684\u662f\u5b50\u83dc\u5355\uff0c\u8bf7\u9009\u62e9\u7236\u83dc\u5355', null=True, on_delete=django.db.models.deletion.SET_NULL, to='publisher.Project', verbose_name='\u7236\u8282\u70b9')),
            ],
            options={
                'ordering': ['-priority', 'id'],
                'verbose_name': '\u9879\u76ee\u914d\u7f6e',
                'verbose_name_plural': '\u9879\u76ee\u914d\u7f6e',
            },
        ),
        migrations.CreateModel(
            name='projectToHost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.IntegerField()),
                ('Project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='publisher.Project', verbose_name='\u9879\u76ee\u540d\u79f0')),
            ],
        ),
        migrations.CreateModel(
            name='projectToService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.IntegerField()),
                ('Project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='publisher.Project', verbose_name='\u9879\u76ee\u540d\u79f0')),
            ],
        ),
        migrations.CreateModel(
            name='projectType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='\u9879\u76ee\u7c7b\u578b')),
            ],
        ),
        migrations.CreateModel(
            name='publisher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(blank=True, max_length=100, null=True, verbose_name='\u5305\u7248\u672c')),
                ('publish_no', models.CharField(blank=True, max_length=100, null=True, verbose_name='\u53d1\u5e03\u53f7')),
                ('createTime', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('runtime', models.DateTimeField(blank=True, null=True)),
                ('pubhosts', models.CharField(blank=True, max_length=100, null=True, verbose_name='\u53d1\u5e03\u4e3b\u673a')),
                ('orderNo', models.CharField(blank=True, max_length=100, null=True, verbose_name='\u5de5\u5355\u53f7')),
                ('status', models.CharField(blank=True, choices=[('0', '\u53d1\u5e03\u4e2d'), ('1', '\u53d1\u5e03\u6210\u529f'), ('2', '\u53d1\u5e03\u5931\u8d25')], max_length=30, null=True, verbose_name='\u53d1\u5e03\u72b6\u6001')),
                ('env', models.IntegerField(blank=True, null=True, verbose_name='\u670d\u52a1\u73af\u5883')),
                ('Project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='publisher.Project', verbose_name='\u9879\u76ee\u540d\u79f0')),
                ('package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='publisher.package', verbose_name='\u5305\u540d\u79f0')),
            ],
        ),
        migrations.CreateModel(
            name='publisherToHost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.IntegerField()),
                ('publisher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='publisher.publisher', verbose_name='\u53d1\u5e03\u540d\u79f0')),
            ],
        ),
        migrations.CreateModel(
            name='service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='\u670d\u52a1\u540d')),
                ('name_en', models.CharField(blank=True, max_length=100, verbose_name='\u670d\u52a1\u82f1\u6587\u540d')),
                ('url', models.CharField(blank=True, max_length=100, null=True, verbose_name='url')),
                ('ip', models.CharField(blank=True, max_length=100, null=True, verbose_name='ip')),
                ('innerUrl', models.CharField(blank=True, max_length=100, null=True, verbose_name='url')),
                ('innerIp', models.CharField(blank=True, max_length=100, null=True, verbose_name='ip')),
                ('env', models.IntegerField(blank=True, null=True, verbose_name='\u670d\u52a1\u73af\u5883')),
                ('hosts', models.CharField(blank=True, max_length=100, null=True, verbose_name='\u4e3b\u673a')),
                ('status', models.CharField(blank=True, choices=[('0', '\u672a\u521d\u59cb\u5316'), ('1', '\u5df2\u521d\u59cb\u5316')], max_length=30, null=True, verbose_name='\u72b6\u6001')),
                ('createTime', models.DateTimeField(blank=True, null=True)),
                ('OutterIpSource', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='publisher.OutterIpSource', verbose_name='\u5916\u90e8IP\u5730\u5740')),
            ],
        ),
        migrations.CreateModel(
            name='serviceToHost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.IntegerField()),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sth', to='publisher.service', verbose_name='\u670d\u52a1\u540d\u79f0')),
            ],
        ),
        migrations.CreateModel(
            name='serviceType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='\u670d\u52a1\u7c7b\u578b')),
            ],
        ),
        migrations.CreateModel(
            name='version',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('build_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='\u6784\u5efa\u53f7')),
                ('jenkins_ver', models.CharField(blank=True, max_length=100, null=True, verbose_name='jenkins\u7248\u672c')),
                ('mdno', models.CharField(blank=True, max_length=100, null=True, verbose_name='md5\u7248\u672c')),
                ('ftpurl', models.CharField(blank=True, max_length=100, null=True, verbose_name='ftpurl')),
                ('createTime', models.DateTimeField(blank=True, null=True)),
                ('finishTime', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('0', '\u6784\u5efa\u4e2d'), ('1', '\u6784\u5efa\u5b8c\u6210'), ('2', '\u6784\u5efa\u5931\u8d25')], max_length=30, null=True, verbose_name='\u6784\u5efa\u72b6\u6001')),
                ('lastbuildinfo', models.CharField(blank=True, max_length=500, null=True, verbose_name='\u6700\u540e\u6784\u5efa\u4fe1\u606f')),
                ('Project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='publisher.Project', verbose_name='\u9879\u76ee\u540d\u79f0')),
            ],
        ),
        migrations.AddField(
            model_name='service',
            name='serviceType',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='publisher.serviceType', verbose_name='\u670d\u52a1\u7c7b\u578b'),
        ),
        migrations.AddField(
            model_name='project',
            name='projectType',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='publisher.projectType', verbose_name='\u9879\u76ee\u7c7b\u578b'),
        ),
        migrations.AddField(
            model_name='host_name',
            name='Project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='publisher.Project', verbose_name='\u9879\u76ee\u540d\u79f0'),
        ),
    ]
