# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-18 10:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('publisher', '0002_auto_20171219_2110'),
    ]

    operations = [
        migrations.CreateModel(
            name='svgelement',
            fields=[
                ('pid', models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='\u9879\u76ee')),
                ('sid', models.CharField(max_length=255, verbose_name='\u670d\u52a1')),
                ('hid', models.CharField(max_length=255, verbose_name='\u4e3b\u673a')),
                ('hname', models.CharField(max_length=255, verbose_name='\u4e3b\u673a\u540d')),
                ('group', models.CharField(max_length=255, verbose_name='\u7ec4')),
            ],
            options={
                'db_table': 'svgelement',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='pubcmd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pubparam', models.CharField(blank=True, max_length=100, null=True, verbose_name='\u8fd0\u884c\u53c2\u6570')),
                ('env', models.IntegerField(blank=True, null=True, verbose_name='\u73af\u5883')),
            ],
            options={
                'verbose_name': '\u53d1\u5e03\u547d\u4ee4\u914d\u7f6e',
                'verbose_name_plural': '\u53d1\u5e03\u547d\u4ee4\u914d\u7f6e',
            },
        ),
        migrations.CreateModel(
            name='version_backup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('build_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='\u6784\u5efa\u53f7')),
                ('ftpurl', models.CharField(blank=True, max_length=100, null=True, verbose_name='ftpurl')),
                ('createTime', models.DateTimeField(blank=True, null=True)),
                ('finishTime', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('0', '\u6784\u5efa\u4e2d'), ('1', '\u6784\u5efa\u5b8c\u6210'), ('2', '\u6784\u5efa\u5931\u8d25')], max_length=30, null=True, verbose_name='\u6784\u5efa\u72b6\u6001')),
                ('bagName', models.CharField(blank=True, max_length=100, null=True, verbose_name='\u5305\u540d')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='jid',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='\u4efb\u52a1\u7f16\u53f7'),
        ),
        migrations.AddField(
            model_name='project',
            name='project_nature',
            field=models.CharField(blank=True, choices=[('0', '\u4e00\u822c\u9879\u76ee'), ('1', '\u91cd\u8981\u9879\u76ee')], max_length=30, null=True, verbose_name='\u9879\u76ee\u5c5e\u6027'),
        ),
        migrations.AddField(
            model_name='project',
            name='publish_type',
            field=models.CharField(blank=True, choices=[('0', 'tomcat'), ('1', 'springboot')], max_length=30, null=True, verbose_name='\u53d1\u5e03\u7c7b\u578b'),
        ),
        migrations.AddField(
            model_name='publisher',
            name='jid',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='\u4efb\u52a1\u7f16\u53f7'),
        ),
        migrations.AddField(
            model_name='publisher',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='\u8d1f\u8d23\u4eba'),
        ),
        migrations.AddField(
            model_name='publisher',
            name='type',
            field=models.CharField(blank=True, choices=[('0', 'tomcat'), ('1', 'springboot')], max_length=30, null=True, verbose_name='\u53d1\u5e03\u7c7b\u578b'),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='Project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='publisher.Project', verbose_name='\u9879\u76ee\u540d\u79f0'),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='orderNo',
            field=models.IntegerField(blank=True, null=True, verbose_name='\u7968\u53f7'),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='pubhosts',
            field=models.CharField(max_length=100, null=True, verbose_name='\u53d1\u5e03\u4e3b\u673a'),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='status',
            field=models.CharField(blank=True, choices=[('0', '\u53d1\u5e03\u4e2d'), ('1', '\u5df2\u53d1\u9001'), ('2', '\u53d1\u5e03\u5931\u8d25'), ('3', '\u4e22\u5f03')], max_length=30, null=True, verbose_name='\u53d1\u5e03\u72b6\u6001'),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='publisher.version', verbose_name='\u6784\u5efa\u7248\u672c'),
        ),
        migrations.AddField(
            model_name='version_backup',
            name='Project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='publisher.Project', verbose_name='\u9879\u76ee\u540d\u79f0'),
        ),
        migrations.AddField(
            model_name='publisher',
            name='pubcmd',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='publisher.pubcmd', verbose_name='\u8fd0\u884c\u53c2\u6570'),
        ),
    ]
