# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-17 09:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('publisher', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='env',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('env_id', models.IntegerField(verbose_name='\u73af\u5883ID')),
                ('shortname', models.CharField(max_length=30, null=True, verbose_name='\u73af\u5883\u540d\u79f0')),
                ('fullname', models.CharField(max_length=30, null=True, verbose_name='\u73af\u5883\u540d\u79f0')),
            ],
        ),
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vip', models.GenericIPAddressField(blank=True, null=True, verbose_name='VIP')),
                ('hostname', models.CharField(max_length=50, verbose_name='\u4e3b\u673a\u540d')),
                ('uuid', models.CharField(max_length=50, unique=True, verbose_name='\u552f\u4e00\u7f16\u53f7')),
                ('ip', models.GenericIPAddressField(verbose_name='IP')),
                ('ilo_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='\u5176\u5b83IP')),
                ('asset_no', models.CharField(blank=True, max_length=50, null=True, verbose_name='\u56fa\u5b9a\u8d44\u4ea7\u7f16\u53f7')),
                ('asset_type', models.CharField(blank=True, choices=[(b'1', '\u7269\u7406\u673a'), (b'2', '\u865a\u62df\u673a')], max_length=30, null=True, verbose_name='\u8bbe\u5907\u7c7b\u578b')),
                ('status', models.CharField(blank=True, choices=[(b'1', '\u672a\u4f7f\u7528'), (b'2', '\u5df2\u6539\u4e3b\u673a\u540d'), (b'3', '\u5df2\u91cd\u65b0\u63a5\u6536key'), (b'4', '\u5df2\u4f7f\u7528'), (b'5', '\u5176\u4ed6')], max_length=30, null=True, verbose_name='\u8bbe\u5907\u72b6\u6001')),
                ('os', models.CharField(blank=True, max_length=100, null=True, verbose_name='\u64cd\u4f5c\u7cfb\u7edf')),
                ('kernel', models.CharField(blank=True, max_length=100, null=True, verbose_name='\u7cfb\u7edf\u7248\u672c')),
                ('kernel_release', models.CharField(blank=True, max_length=100, null=True, verbose_name='\u5185\u6838\u7248\u672c')),
                ('vendor', models.CharField(blank=True, max_length=50, null=True, verbose_name='\u8bbe\u5907\u5382\u5546')),
                ('cpu_model', models.CharField(blank=True, max_length=100, null=True, verbose_name='CPU\u578b\u53f7')),
                ('cpu_num', models.IntegerField(blank=True, null=True, verbose_name='CPU\u6570\u91cf')),
                ('memory', models.CharField(blank=True, max_length=30, null=True, verbose_name='\u5185\u5b58\u5927\u5c0f')),
                ('disk', models.CharField(blank=True, max_length=255, null=True, verbose_name='\u786c\u76d8\u5927\u5c0f')),
                ('disks', models.CharField(blank=True, max_length=255, null=True, verbose_name='\u786c\u76d8\u4fe1\u606f')),
                ('sn', models.CharField(blank=True, max_length=60, verbose_name='SN\u53f7 \u7801')),
                ('position', models.CharField(blank=True, max_length=100, null=True, verbose_name='\u6240\u5728\u4f4d\u7f6e')),
                ('memo', models.TextField(blank=True, max_length=200, null=True, verbose_name='\u5907\u6ce8\u4fe1\u606f')),
                ('terminal_time', models.DateTimeField(null=True, verbose_name='\u8fc7\u671f\u65e5\u671f')),
                ('create_time', models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='\u521b\u5efa\u65e5\u671f')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='\u6700\u540e\u4fee\u6539\u65e5\u671f')),
                ('re_per', models.CharField(blank=True, max_length=100, null=True, verbose_name='\u8d1f\u8d23\u4eba')),
                ('mac', models.CharField(blank=True, max_length=100, null=True, verbose_name='mac\u5730\u5740')),
            ],
            options={
                'verbose_name': '\u670d\u52a1\u5668\u914d\u7f6e',
                'verbose_name_plural': '\u670d\u52a1\u5668\u914d\u7f6e',
            },
        ),
        migrations.CreateModel(
            name='HostGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='\u7ec4\u540d')),
                ('desc', models.CharField(blank=True, max_length=100, null=True, verbose_name='\u63cf\u8ff0')),
            ],
            options={
                'verbose_name': '\u8bbe\u5907\u7ec4\u914d\u7f6e',
                'verbose_name_plural': '\u8bbe\u5907\u7ec4\u914d\u7f6e',
            },
        ),
        migrations.CreateModel(
            name='Idc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, null=True, verbose_name='\u673a\u623f\u540d\u79f0')),
                ('address', models.CharField(max_length=100, null=True, verbose_name='\u673a\u623f\u5730\u5740')),
                ('tel', models.CharField(max_length=30, null=True, verbose_name='\u673a\u623f\u7535\u8bdd')),
                ('contact', models.CharField(max_length=30, null=True, verbose_name='\u5ba2\u6237\u7ecf\u7406')),
                ('contact_phone', models.CharField(max_length=30, null=True, verbose_name='\u79fb\u52a8\u7535\u8bdd')),
                ('jigui', models.CharField(max_length=30, null=True, verbose_name='\u673a\u67dc\u4fe1\u606f')),
                ('ip_range', models.CharField(max_length=30, null=True, verbose_name='IP\u8303\u56f4')),
                ('bandwidth', models.CharField(max_length=30, null=True, verbose_name='\u63a5\u5165\u5e26\u5bbd')),
            ],
            options={
                'verbose_name': '\u6570\u636e\u4e2d\u5fc3\u914d\u7f6e',
                'verbose_name_plural': '\u6570\u636e\u4e2d\u5fc3\u914d\u7f6e',
            },
        ),
        migrations.CreateModel(
            name='InterFace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('vendor', models.CharField(max_length=30, null=True)),
                ('bandwidth', models.CharField(max_length=30, null=True)),
                ('tel', models.CharField(max_length=30, null=True)),
                ('contact', models.CharField(max_length=30, null=True)),
                ('startdate', models.DateField()),
                ('enddate', models.DateField()),
                ('price', models.IntegerField(verbose_name='\u4ef7\u683c')),
            ],
            options={
                'verbose_name': '\u7ebf\u8def\u914d\u7f6e',
                'verbose_name_plural': '\u7ebf\u8def\u914d\u7f6e',
            },
        ),
        migrations.CreateModel(
            name='IpSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vlan_id', models.IntegerField(verbose_name='VLAN_ID')),
                ('subnet', models.CharField(max_length=30, null=True)),
                ('describe', models.CharField(max_length=30, null=True)),
                ('area', models.CharField(max_length=30, null=True)),
                ('env', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cmdb.env')),
            ],
            options={
                'verbose_name': '\u73af\u5883\u914d\u7f6e',
                'verbose_name_plural': '\u73af\u5883\u914d\u7f6e',
            },
        ),
        migrations.CreateModel(
            name='Manufactory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_name', models.CharField(max_length=30)),
                ('asset_type', models.CharField(blank=True, choices=[(b'1', '\u7269\u7406\u673a'), (b'2', '\u865a\u62df\u673a')], max_length=30, null=True, verbose_name='\u8bbe\u5907\u7c7b\u578b')),
            ],
        ),
        migrations.AddField(
            model_name='host',
            name='env',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cmdb.IpSource', verbose_name='\u6240\u5c5e\u73af\u5883'),
        ),
        migrations.AddField(
            model_name='host',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmdb.HostGroup', verbose_name='\u8bbe\u5907\u7ec4'),
        ),
        migrations.AddField(
            model_name='host',
            name='idc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cmdb.Idc', verbose_name='\u6240\u5728\u6570\u636e\u4e2d\u5fc3'),
        ),
        migrations.AddField(
            model_name='host',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='publisher.Project', verbose_name='\u9879\u76ee\u7ec4'),
        ),
    ]
