# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-19 13:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='jenkins_source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vlan_id', models.IntegerField(verbose_name='VLAN_ID')),
                ('subnet', models.CharField(max_length=30, null=True)),
                ('describe', models.CharField(max_length=30, null=True)),
                ('area', models.CharField(max_length=30, null=True)),
            ],
            options={
                'verbose_name': '\u73af\u5883\u914d\u7f6e',
                'verbose_name_plural': '\u73af\u5883\u914d\u7f6e',
            },
        ),
        migrations.AddField(
            model_name='env',
            name='jenkins_port',
            field=models.CharField(max_length=100, null=True, verbose_name='jenkins\u7aef\u53e3'),
        ),
        migrations.AddField(
            model_name='env',
            name='jenkins_pwd',
            field=models.CharField(max_length=100, null=True, verbose_name='jenkins\u5bc6\u7801'),
        ),
        migrations.AddField(
            model_name='env',
            name='jenkins_url',
            field=models.CharField(max_length=100, null=True, verbose_name='jenkins_url'),
        ),
        migrations.AddField(
            model_name='env',
            name='jenkins_username',
            field=models.CharField(max_length=100, null=True, verbose_name='jenkins\u7528\u6237\u540d'),
        ),
        migrations.AddField(
            model_name='env',
            name='sftp_url',
            field=models.CharField(max_length=100, null=True, verbose_name='sftp_url'),
        ),
        migrations.AddField(
            model_name='jenkins_source',
            name='env',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cmdb.env'),
        ),
    ]
